on:
  push:
  workflow_dispatch:
jobs:
  test:
    name: deploy to staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Install Python
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
        # Run pytest
      - name: Run tests
        continue-on-error: true
        run: |
          pytest
      # Write Pytest overview results to a file
      - name: Record test results
        if: '!cancelled()'
        run: |
          pytest -r N --tb=no > ./.util/marking.txt || true
      # Convert results to JSON
      - name: Convert result format
        if: '!cancelled()'
        run: |
          cd .util
          python3 convert_to_json.py
          cd ..
      # Commit results
      - name: Push results
        if: '!cancelled()'
        run: |
          git config --global user.name 'Peritract'
          git config --global user.email 'peritract@users.noreply.github.com'
          git add .util/marking.txt .util/marking.json
          git commit -m "Assessment testing"
          git push
