on:
  push:
  workflow_dispatch:
jobs:
  test:
    name: deploy to staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Install Python
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
        # Run pytest
      - name: Run tests
        continue-on-error: true
        run: pytest
